In [1]:
import math
import numpy as np
from numpy import linalg as LA
import random
from numpy.linalg import inv

In [ ]:
math.sin(math.sqrt(2)*math.pi)

In [ ]:
#Rosenbrock function
def f(xk):
    x1 = xk[0]
    x2 = xk[1]
    func=100*(x2 - x1**2)**2 +(1-x1)**2
    return func

In [ ]:
def gradientf(xk):
    x1 = xk[0]
    x2= xk[1]
    div1=-400*x1*(x2-x1**2)- 2*(1-x1)**2
    div2= 200*(x2-x1**2)
    return np.array(np.array([div1,div2],dtype=float))

In [ ]:
def pk(xk):
    pk= - gradientf(xk)
    return pk

In [ ]:
xk=(0,0)
a=0.3
x_new= xk + a*pk(xk)
f(x_new) 

In [ ]:
def backtracking (a, xk):
    rho=0.5
    c1= math.pow(10,-4)
    x_new= xk + a*pk(xk)    
    while( f(x_new)> (f(xk) + c1*a*gradientf(xk)@pk(xk))):
        print("a is:", a)
        print("f(x_new) is:", f(x_new))
        print( "f(xk)+ac1*Gradf*pk:", f(xk) + c1*a*gradientf(xk) @ pk(xk))
        a=rho*a
        x_new= xk + a*pk(xk)  
    print("The armijo is True so the algorithm ends, the step value is:")
    return a

In [ ]:
xk=(0,0)
backtracking(0.3,xk)

In [ ]:
def phi(xk,a):
    xnew=xk+a*pk(xk)
    return f(xnew)

In [ ]:
def Gradphi(xk,a):
    new=xk + a*pk(xk)
    return gradientf(new)@pk(xk)

In [ ]:
def zoom(a_low,a_high):
    c1=math.pow(10,-4)
    c2=0.9
    t = 0
    while True:
        aj = (a_high + a_low)/2
        print("aj is",aj)
        if (phi(xk,aj) > phi(xk,0) + c1*aj*Gradphi(xk,0)) or (phi(xk,aj) >=phi(xk,a_low)):
            print("MPIKA PRWTO IF")
            a_high = aj
        else:
            phi_grad_aj=abs(Gradphi(xk,aj))
            print("MPIKA ELSE")
            if (phi_grad_aj <= -c2*Gradphi(xk,0)):
                aastro = aj
                return aastro

            if ((Gradphi(xk,aj)*(a_high-a_low)) >= 0 ) :
                print("MPIKA EDW")
                a_high = a_low

            a_low = aj
        t= t+1

In [ ]:
def linesearch(xk):
    amax=1
    ai=0 #a0=0
    a_minus=0
    i=1
    c1 = math.pow(10,-4)
    c2 = 0.9
    while True:
        if((phi(xk,ai)> phi(xk,0) +c1*ai*Gradphi(xk,0)) or (phi(xk,ai)>=phi(xk, a_minus) and (i>1))):
            print("MPIKA ZOOM")
            aastro= zoom(a_minus, ai)
            return aastro
        if ( abs(Gradphi(xk,ai)) <= -c2*Gradphi(xk,0)):
            aastro= ai 
            return aastro
        if ( Gradphi(xk,ai)>=0 ):
            aastro= zoom(ai, a_minus)
            return aastro
        a_minus=ai
        ai= random.uniform(ai, amax)
        print("ai is:",ai)
        i= i +1

In [ ]:
xk=(-0.5,0.5)

In [ ]:
def Hessianr(xk):
    x1=xk[0]
    x2=xk[1]
    dx1x1= 1200 * x1**2 - 400*x2 +2
    dx1x2= - 400*x1
    dx2x1= - 400*x1
    dx2x2= 200
    h= np.array([[dx1x1, dx1x2], [dx2x1, dx2x2]])
    return h

In [ ]:
def pnewton(xk):
    pn= - inv(Hessian(xk)) @ gradientf(xk)
    return pn

In [ ]:
i=np.array([[1,1],[0,1]])
eign=LA.eig(i)
eign[0]

In [ ]:
epsilon= math.pow(10,-3)
gk=gradientf(xk)
k=0
while (LA.norm(gk)>=epsilon):
    ak=linesearch(xk)
    print("ak is:",ak)
    xnew=xk+ak*pk(xk)
    print("the new position is:",xnew)
    print("fvalue", f(xnew))
    gk=gradientf(xnew)
    xk=xnew
    k=k+1
    print("itteration:",k)

In [ ]:
xk=(-0.5,0.5)
eing=LA.eig(Hessian(xk))[0]
eing.all()>0

In [ ]:
epsilon= math.pow(10,-3)
gk=gradientf(xk)
k=0
while (LA.norm(gk)>=epsilon):
    ak=linesearch(xk)
    print("ak is:",ak)
    eing=LA.eig(Hessian(xk))[0]
    if eing.all()> 0:
        xnew=xk+ak*pnewton(xk)
        print("the new position is:",xnew)
        print("fvalue", f(xnew))
        gk=gradientf(xnew)
        xk=xnew
        k=k+1
        print("itteration:",k)
    else:
        print("Matrix has to change, it's not positive!")

# Griewank function for test 1

In [2]:
def gw(xk):
    x1=xk[0]
    x2=xk[1]
    f=1 + (1/4000) *(x1**2 + x2**2) - math.cos(x1)* math.cos((x2/math.sqrt(2)))
    return f

In [3]:
def gradgw(xk):
    x1=xk[0]
    x2=xk[1]
    dx1=(1/2000)*x1 + math.sin(x1)*math.cos((x2/math.sqrt(2)))
    dx2= (1/2000)*x2 + (1/math.sqrt(2))*math.cos(x1)*math.sin((x2/math.sqrt(2)))
    return np.array(np.array([dx1,dx2],dtype=float))

# Armijo testing 

In [6]:
def armijo(xk,pk,ak):
    #xk= (math.pi, math.sqrt(2)*math.pi)
    #pk=(math.pi, - math.sqrt(2)*math.pi)
    c1=0.0001
    xnew= np.add(xk, np.multiply(pk,ak))
    print(xnew)
    print(gw(xnew))
    print(gw(xk) + c1* ak * gradgw(xk)@pk)
    return (gw(xnew) <= (gw(xk) + c1* ak * gradgw(xk)@pk))

In [4]:
xk= (math.pi, math.sqrt(2)*math.pi)
pk=(math.pi, - math.sqrt(2)*math.pi)

In [7]:
ak=0.01
armijo(xk,pk,ak)

[3.17300858 4.39845411]
0.008340231285005828
0.007402198366014778


False

# sinthiki kampilotitas

In [41]:
def kampyl(xk,pk,ak):
    c2= random.uniform(0.0001,1)
    xnew= np.add(xk, np.multiply(pk,ak))
    return gradgw(xnew)@pk >= np.multiply(c2, gradgw(xk)@pk)

In [42]:
ak=1
kampyl(xk,pk,ak)

0.009869604401088588
-0.004195396720365627


True

In [ ]:
def Hessian(xk):
    x1=xk[0]
    x2=xk[1]
    dx1x1= (1/2000) + math.cos(x1)* math.cos(x2/math.sqrt(2))
    dx1x2= - math.sin(x1)*math.sin(x2/math.sqrt(2))*(1/math.sqrt(2))
    dx2x1= - math.sin(x1)*math.sin(x2/math.sqrt(2))*(1/math.sqrt(2))
    dx2x2= (1/2000)+ (1/2)*math.cos(x1)*math.cos(x2/math.sqrt(2))
    h= np.array([[dx1x1, dx1x2], [dx2x1, dx2x2]])
    return h

In [ ]:
# Don't forget to check if the inv Hessian is positive

In [ ]:
eign= LA.eig(Hessian(xk))
eign[0].all() >0

In [ ]:
def pnewton(xk):
    pn= - LA.inv(Hessian(xk)) @ gradgw(xk)
    return pn

In [ ]:
pnewton(xk)

In [ ]:
A=np.array([[4.,6.,10.],[6.,25.,19.],[10.,19.,62.]])
L=np.linalg.cholesky(A)
print('L=',L)
print('\n')
print('LL.T=',np.dot(L,L.T))

In [ ]:
I=np.identity(len(A))
A+ 2*I

# conert to possitive definite matrix

In [43]:
def make_positive(H):
    b=1
    I = np.identity(len(H))
    if (min(np.diagonal(H))>0):
        tk=0
    else:
        tk= - min(np.diagonal(H)) + b
    while True:
        try:
            ar= H + tk* I
            L=np.linalg.cholesky(ar)
            return L
        except:
            tk= max(2*tk, b)

In [52]:
A=np.array([[2,-1,-1],[-1,-2,1],[-1,1,-10]])
L=make_positive(A)
L@L.T

array([[13., -1., -1.],
       [-1.,  9.,  1.],
       [-1.,  1.,  1.]])

# Trust region test 2

In [56]:
#Newton point
H= np.array([[2,4,-2], [4,16,-4],[-2,-4,4]])
LA.eig(H)[0].all()>0
gk=np.array([4,8,-4])
k=LA.inv(H)
p_B= - k@gk
LA.norm(p_B) #we dont accept Newton point for radius =1

2.0

In [57]:
#cauchy point
x=gk.transpose()@gk
y=gk.transpose() @ H @ gk
pU= - np.multiply((x/y), gk)
LA.norm(pU)  #we dont accept cachy point for radius =1 

0.5546014511961913

In [60]:
f = lambda t: math.pow( LA.norm(pU + np.multiply((t-1),(p_B - pU))), 2) - 1
f

<function __main__.<lambda>(t)>

In [61]:
def bisection(f,a,b,N):
    if f(a)*f(b) >= 0:
        print("Bisection method fails.")
        return None
    a_n = a
    b_n = b
    for n in range(1,N+1):
        m_n = (a_n + b_n)/2
        f_m_n = f(m_n)
        if f(a_n)*f_m_n < 0:
            a_n = a_n
            b_n = m_n
        elif f(b_n)*f_m_n < 0:
            a_n = m_n
            b_n = b_n
        elif f_m_n == 0:
            print("Found exact solution.")
            return m_n
        else:
            print("Bisection method fails.")
            return None
    return (a_n + b_n)/2

In [65]:
t=bisection(f,1,2,100)
t

1.4104709106062039

In [66]:
pastro= pU + np.multiply((t-1), p_B - pU)
pastro

array([-0.95442011, -0.26695657,  0.13347828])

 erwtisi 4. Syzigis dieuthinseis

In [13]:
def gradf3(xk):
    x1=xk[0]
    x2=xk[1]
    x3=xk[2]
    div1= 2*(x1 + x2**2  - math.log(x3))
    div2= 4* x2 *( x1+ x2**2 - math.log(x3))
    div3= -2*(x1 + x2**2 - math.log(x3))*(1/x3)
    return np.array(np.array([div1,div2,div3],dtype=float))

In [26]:
xkplus=(0.6,0.2,1.4)
xk=(1,1,1)
p0= - gradf3(xk)
grad_fxkplus=gradf3(xkplus)
grad_fxk= gradf3(xk)
b_FR = (grad_fxkplus.transpose() @ grad_fxkplus)/ (grad_fxk.transpose() @ grad_fxk)
p1_FR= - grad_fxkplus + np.multiply( b_FR, p0)
b_PR = (grad_fxkplus.transpose() @ (grad_fxkplus - grad_fxk))/ (math.pow(LA.norm(grad_fxk),2))
p1_PR = - grad_fxkplus + np.multiply(b_PR, p0)

-0.05718485977501195

In [29]:
b_PR_max=max(b_PR,0)
p1_PR_max = - grad_fxkplus + np.multiply(b_PR_max, p0)
p1_PR_max

array([-0.60705553, -0.24282221,  0.43361109])

# Test 3

In [8]:
simple= list()
# ro operators
ro_reflection = 1
ro_expansion = 2 * ro_reflection
ro_external_contraction = 0.5 * ro_reflection
ro_internal_contraction = -0.5
x1=(0,0)
x2=(1,1)
x3=(-2,1)
def f4(xk):
    x1=xk[0]
    x2=xk[1]
    return 2*(x1**2) - x2**2

In [35]:
f1=f4(x1)
f2=f4(x2)
f3=f4(x3)
x_meso= np.add(x1,x2)/2
x_ref= np.multiply((1+ ro_reflection),x_meso) - np.multiply(ro_reflection,x3)
fref=f4(x_ref)
f1 <= fref < f2 #False, so we continue.
fref< f1 #False
f2<=fref<f3 #False
f3<=fref #True!!!
xinc=np.multiply((1+ ro_internal_contraction),x_meso) - np.multiply(ro_internal_contraction,x3)
finc=f4(xinc)
finc<f3 #True!!! opote krataw to finc sto aploko sti thesi tou x3
finc

0.5625

In [82]:
H=np.array([[10,8],[8,10]])
from numpy.linalg import inv
inv=inv(H)
LA.eig(inv)[0]
LA.eig(H)[0]

array([18.,  2.])

# exams

In [8]:
def f(xk):
    x=xk[0]
    y=xk[1]
    return (x+2*y-7)**2 + (2*x+y-5)**2

In [11]:
def gradf(xk):
    x=xk[0]
    y=xk[1]
    div1= 10*x+8*y-34
    div2= 8*x+10*y-38
    return np.array(np.array([div1,div2],dtype=float))

In [15]:
def p(xk,pk):
    return gradf(xk)@pk <0

In [81]:
xk=(1,1)
pk=(1.0000,-0.1523)
cos= -(pk@gradf(xk))/(LA.norm(pk)*LA.norm(gradf(xk)))
cos

0.500003111417426

In [45]:
def arm(xk,pk,ak):
    c1=0.0001
    xnew= np.add(xk, np.multiply(pk,ak))
    print(f(xk) + c1* ak * gradf(xk)@pk)
    print(f(xnew))
    return (f(xnew) <= (f(xk) + c1* ak * gradf(xk)@pk))

In [48]:
pk=(16,20)
c1=0.0001
ak=0.056
c1* ak * gradf(xk)@pk +20

19.9963264

In [49]:
def f1(xk):
    x1=xk[0]
    x2=xk[1]
    return (x1**2 +x2**2)**2

In [56]:
def gradf1(xk):
    x1=xk[0]
    x2=xk[1]
    div1= 4*math.pow(x1,3) + 4*x1*math.pow(x2,2)
    div2= 4*math.pow(x2,3) + 4*x2*math.pow(x1,2)
    return np.array(np.array([div1,div2],dtype=float))

In [65]:
def arm(xk,pk,ak):
    c1=0.1
    xnew= np.add(xk, np.multiply(pk,ak))
    print(xnew)
    print(f1(xk) + c1* ak * gradf1(xk)@pk)
    print(f1(xnew))
    return (f1(xnew) <= (f1(xk) + c1* ak * gradf1(xk)@pk))

In [87]:
A=np.array([[1.0005,0],[0,0.5005]])
LA.eig(A)[0]

array([1.0005, 0.5005])

In [76]:
xk=(3,2)
pk=(0.5,9)
arm(xk,pk,0.5)
f1(xk)

[3.25 6.5 ]
219.7
2789.16015625


169

In [74]:
def kampyl(xk,pk,ak):
    c2= 0.9
    xnew= np.add(xk, np.multiply(pk,ak))
    return gradf1(xnew)@pk >= np.multiply(c2, gradf1(xk)@pk)

In [75]:
kampyl(xk,pk,0.5)

True

# exams

In [8]:
def gradf(xk):
    x=xk[0]
    y=xk[1]
    div1=  4*(x**3)+4*x*y -42*x+2*(y**2)-14
    div2= 2*(x**2)+4*(y**3)+4*y*x -26*y-22
    return np.array(np.array([div1,div2],dtype=float))

In [12]:
def f(xk):
    x=xk[0]
    y=xk[1]
    return (x**2 +y -11)**2 +(x+y**2 -7)**2

In [9]:
xk=(1,1)
gradf(xk)

array([-46., -38.])

In [18]:
def armijo(xk,pk,ak):
    c1=0.0001
    xnew= np.add(xk, np.multiply(pk,ak))
    print(xnew)
    print(f(xnew))
    print(f(xk) + c1* ak * gradf(xk)@pk)
    return (f(xnew) <= (f(xk) + c1* ak * gradf(xk)@pk))

In [39]:
xk=(1,1)
pk=-gradf(xk)
armijo(xk,pk,0.01)

[1.46 1.38]
69.29372192000001
105.99644


True

In [44]:
def kampyl(xk,pk,ak):
    c2= 0.9
    xnew= np.add(xk, np.multiply(pk,ak))
    return gradf(xnew)@pk >= np.multiply(c2, gradf(xk)@pk)

In [45]:
xk=(1,1)
pk= -gradf(xk)
kampyl(xk,pk,0.01)

False

In [28]:
A= np.array([[-26,8],[8,-10]])
invers=LA.inv(A)
LA.eig(invers)[0]

array([-0.03411373, -0.14955974])

In [29]:
def make_positive(H):
    b=1
    I = np.identity(len(H))
    if (min(np.diagonal(H))>0):
        tk=0
    else:
        tk= - min(np.diagonal(H)) + b
    while True:
        try:
            ar= H + tk* I
            L=np.linalg.cholesky(ar)
            return L
        except:
            tk= max(2*tk, b)

In [37]:
L=make_positive(A)
L@L.T

array([[28.,  8.],
       [ 8., 44.]])

In [35]:
k=L@L.T
LA.eig(k)[0]

array([24.6862915, 47.3137085])

In [36]:
2/(10**(-3))

2000.0